### ISSUE TITLE
misses solutions when fitnessEvaluator time varies

### ISSUE THREAD

**Issue by adirz** [rubenjgarcia/genetical#1]
I have something that takes a long time to check fitnessEvaluator, it changes drastically and asynchronously. It doesn't wait for it to finish (everybody calling the cb function), so I end up getting only the first to finish, instead of the one with best score

**Comment by rubenjgarcia** [comment]
Can you provide an example?

**Comment by adirz** [comment]
I figure it might be a problem on my end, so don't consider it for now, until I finish testing, sorry if I bother you for nothing

**Comment by rubenjgarcia** [comment]
Ok. Let me know if you find anything wrong about the library code :wink:
